INSERT INTO barangays (name, city, province, created_at)
SELECT * FROM (VALUES
  ('Barangay 1', 'Manila', 'Metro Manila', NOW()),
  ('Barangay 2', 'Manila', 'Metro Manila', NOW()),
  ('Barangay 3', 'Manila', 'Metro Manila', NOW()),
  ('Barangay 4', 'Manila', 'Metro Manila', NOW()),
  ('Barangay 5', 'Manila', 'Metro Manila', NOW()),
  ('Barangay 6', 'Manila', 'Metro Manila', NOW()),
  ('Barangay 7', 'Manila', 'Metro Manila', NOW()),
  ('Tondo', 'Manila', 'Metro Manila', NOW()),
  ('Binondo', 'Manila', 'Metro Manila', NOW()),
  ('Ermita', 'Manila', 'Metro Manila', NOW()),
  ('Malate', 'Manila', 'Metro Manila', NOW()),
  ('Paco', 'Manila', 'Metro Manila', NOW()),
  ('Pandacan', 'Manila', 'Metro Manila', NOW()),
  ('Sampaloc', 'Manila', 'Metro Manila', NOW()),
  ('Santa Ana', 'Manila', 'Metro Manila', NOW()),
  ('Santa Cruz', 'Manila', 'Metro Manila', NOW()),
  ('Quiapo', 'Manila', 'Metro Manila', NOW()),
  ('Bagong Silang', 'Caloocan', 'Metro Manila', NOW()),
  ('Deparo', 'Caloocan', 'Metro Manila', NOW()),
  ('Grace Park', 'Caloocan', 'Metro Manila', NOW()),
  ('Bagumbayan', 'Quezon City', 'Metro Manila', NOW()),
  ('Batasan Hills', 'Quezon City', 'Metro Manila', NOW()),
  ('Commonwealth', 'Quezon City', 'Metro Manila', NOW()),
  ('Cubao', 'Quezon City', 'Metro Manila', NOW()),
  ('Diliman', 'Quezon City', 'Metro Manila', NOW()),
  ('Fairview', 'Quezon City', 'Metro Manila', NOW()),
  ('Payatas', 'Quezon City', 'Metro Manila', NOW()),
  ('San Andres', 'Mandaluyong', 'Metro Manila', NOW()),
  ('Barangka', 'Mandaluyong', 'Metro Manila', NOW()),
  ('Highway Hills', 'Mandaluyong', 'Metro Manila', NOW()),
  ('Addition Hills', 'Mandaluyong', 'Metro Manila', NOW())
) AS v(name, city, province, created_at)
WHERE NOT EXISTS (SELECT 1 FROM barangays LIMIT 1);